-- === CREATE SCHEMA real_estate_hub ===
CREATE SCHEMA IF NOT EXISTS real_estate_hub;

-- === TABLE Propyte_desarrolladores ===
CREATE TABLE real_estate_hub."Propyte_desarrolladores" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_id" integer,
  "nombre_desarrollador" character varying(255) NOT NULL,
  "ext_slug_desarrollador" character varying(255),
  "logo" text,
  "sitio_web" text,
  "descripcion" text,
  "ext_descripcion_en" text,
  "nombre_contacto" text,
  "puesto_contacto" text,
  "telefono" text,
  "email" text,
  "redes_sociales" jsonb,
  "es_verificado" boolean DEFAULT false,
  "calificacion" numeric(3,2),
  "proyectos_activos" integer DEFAULT 0,
  "unidades_entregadas" integer DEFAULT 0,
  "anos_experiencia" integer,
  "proyectos_entregados" integer DEFAULT 0,
  "ext_ciudad" text,
  "ext_estado" text,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "deleted_at" timestamp with time zone,
  "zoho_record_id" text,
  "zoho_last_synced_at" timestamp with time zone,
  "zoho_sync_error" text,
  "approved_at" timestamp with time zone,
  "approved_by" text,
  "zoho_pipeline_status" text DEFAULT 'discovery'::text,
  CONSTRAINT "Propyte_desarrolladores_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_desarrolladores_ext_slug_desarrollador_key" UNIQUE ("ext_slug_desarrollador")
);

-- === TABLE Propyte_desarrollos ===
CREATE TABLE real_estate_hub."Propyte_desarrollos" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_id" integer,
  "nombre_desarrollo" character varying(255) NOT NULL,
  "ext_slug_desarrollo" character varying(255),
  "tipo_desarrollo" text,
  "etapa_construccion" text,
  "avance_obra_porcentaje" integer,
  "fecha_entrega" date,
  "ext_fecha_entrega_texto" text,
  "unidades_totales" integer,
  "unidades_disponibles" integer,
  "fases_totales" integer,
  "fase_actual" text,
  "tasa_absorcion" numeric(5,2),
  "arquitecto" text,
  "concepto_diseno" text,
  "url_drive_general" text,
  "fotos_desarrollo" text[],
  "lista_precios" text,
  "brochure_pdf" text,
  "tour_virtual_desarrollo" text,
  "masterplan" text,
  "video_desarrollo" text,
  "ext_og_image_desarrollo" text,
  "ext_precio_min_mxn" numeric(15,2),
  "ext_precio_max_mxn" numeric(15,2),
  "ext_moneda" text DEFAULT 'MXN'::text,
  "ext_roi_proyectado" numeric(5,2),
  "ext_roi_renta_mensual" numeric(5,2),
  "ext_roi_apreciacion" numeric(5,2),
  "ext_enganche_porcentaje" numeric(5,2),
  "ext_meses_financiamiento" integer[],
  "ext_tasa_interes" numeric(5,2),
  "ext_descripcion_es" text,
  "ext_descripcion_en" text,
  "ext_descripcion_corta_es" text,
  "ext_descripcion_corta_en" text,
  "ext_texto_brochure" text,
  "ext_meta_title_desarrollo" text,
  "ext_meta_description_desarrollo" text,
  "ext_keywords" text[],
  "ext_destacado" boolean DEFAULT false,
  "ext_publicado" boolean DEFAULT false,
  "pais" text DEFAULT 'México'::text,
  "estado" text NOT NULL,
  "municipio" text,
  "ciudad" text NOT NULL,
  "colonia" text,
  "calle" text,
  "ext_numero_exterior" text,
  "ext_numero_interior" text,
  "codigo_postal" text,
  "latitud" numeric(10,7),
  "longitud" numeric(10,7),
  "zona" text,
  "link_maps" text,
  "ext_referencias_ubicacion" text,
  "playa_distancia" text,
  "aeropuerto_nombre" text,
  "aeropuerto_distancia" text,
  "supermercado_distancia" text,
  "hospital_distancia" text,
  "puntos_interes" jsonb,
  "amenidad_alberca_privada" boolean DEFAULT false,
  "amenidad_alberca_comunitaria" boolean DEFAULT false,
  "amenidad_gym" boolean DEFAULT false,
  "amenidad_salon_eventos" boolean DEFAULT false,
  "amenidad_coworking" boolean DEFAULT false,
  "amenidad_rooftop" boolean DEFAULT false,
  "amenidad_fire_pit" boolean DEFAULT false,
  "amenidad_yoga" boolean DEFAULT false,
  "amenidad_jardin_privado" boolean DEFAULT false,
  "amenidad_jardin_comunitario" boolean DEFAULT false,
  "amenidad_spa" boolean DEFAULT false,
  "amenidad_restaurante" boolean DEFAULT false,
  "amenidad_concierge" boolean DEFAULT false,
  "amenidad_seguridad_24h" boolean DEFAULT false,
  "amenidad_cctv" boolean DEFAULT false,
  "amenidad_acceso_controlado" boolean DEFAULT false,
  "amenidad_lobby" boolean DEFAULT false,
  "amenidad_elevador" boolean DEFAULT false,
  "amenidad_bodega" boolean DEFAULT false,
  "amenidad_pet_zone" boolean DEFAULT false,
  "amenidad_cancha" boolean DEFAULT false,
  "amenidad_area_ninos" boolean DEFAULT false,
  "ext_amenidad_juice_bar" boolean DEFAULT false,
  "ext_amenidad_service_room" boolean DEFAULT false,
  "amenidades_adicionales" jsonb,
  "ext_crm_relationship" text,
  "ext_commission_rate" numeric(5,2),
  "ext_reserved_units" integer,
  "ext_sold_units" integer,
  "ext_property_types" text[],
  "ext_usage" text[],
  "ext_badge" text,
  "ext_plaza" text,
  "ext_contacto_nombre" text,
  "ext_contacto_telefono" text,
  "ext_detection_source" text,
  "ext_source_url" text,
  "ext_detected_at" timestamp with time zone,
  "id_desarrollador" uuid,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "deleted_at" timestamp with time zone,
  "zoho_pipeline_status" text DEFAULT 'discovery'::text,
  "zoho_record_id" text,
  "zoho_last_synced_at" timestamp with time zone,
  "zoho_sync_error" text,
  "approved_at" timestamp with time zone,
  "approved_by" text,
  CONSTRAINT "Propyte_desarrollos_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_desarrollos_ext_slug_desarrollo_key" UNIQUE ("ext_slug_desarrollo")
);

-- === TABLE Propyte_unidades ===
CREATE TABLE real_estate_hub."Propyte_unidades" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "legacy_id" integer,
  "slug_unidad" character varying(255),
  "titulo_unidad" character varying(255),
  "subtitulo_unidad" character varying(255),
  "descripcion_corta_unidad" text,
  "descripcion_larga_unidad" text,
  "ext_descripcion_en" text,
  "estado_unidad" text,
  "es_nueva_unidad" boolean DEFAULT false,
  "es_destacada_unidad" boolean DEFAULT false,
  "es_preventa" boolean DEFAULT false,
  "tipo_unidad" text,
  "subtipo_unidad" text,
  "ext_numero_unidad" text,
  "ext_tipologia" text,
  "ext_publicado" boolean DEFAULT false,
  "ext_tags" text[],
  "recamaras" integer,
  "banos_completos" integer,
  "medios_banos" integer,
  "superficie_total_m2" numeric(10,2),
  "superficie_construida_m2" numeric(10,2),
  "superficie_terreno_m2" numeric(10,2),
  "niveles_unidad" integer,
  "piso_numero" integer,
  "estacionamientos" integer,
  "orientacion" text,
  "vista_unidad" text,
  "amueblado" boolean DEFAULT false,
  "equipado" boolean DEFAULT false,
  "mascotas_permitidas" boolean,
  "uso_suelo_unidad" text,
  "ext_tiene_alberca" boolean DEFAULT false,
  "precio_mxn" numeric(15,2),
  "precio_usd" numeric(15,2),
  "precio_m2_mxn" numeric(15,2),
  "precio_m2_usd" numeric(15,2),
  "moneda_principal" text DEFAULT 'MXN'::text,
  "precio_desde" numeric(15,2),
  "tipo_entrega" text,
  "financiamiento_directo" boolean,
  "acepta_hipotecario" boolean,
  "acepta_infonavit" boolean,
  "ext_acepta_fovissste" boolean,
  "enganche_porcentaje" numeric(5,2),
  "ext_enganche_mxn" numeric(15,2),
  "ext_meses_financiamiento" text,
  "ext_tasa_interes" numeric(5,2),
  "ext_mensualidad_mxn" numeric(15,2),
  "ext_esquema_pago" text,
  "ext_precio_venta" numeric(15,2),
  "roi_anual_porcentaje" numeric(5,2),
  "roi_1_ano_porcentaje" numeric(5,2),
  "roi_3_anos_porcentaje" numeric(5,2),
  "roi_5_anos_porcentaje" numeric(5,2),
  "renta_mensual_estimada_mxn" numeric(15,2),
  "cash_on_cash_porcentaje" numeric(5,2),
  "punto_equilibrio_meses" integer,
  "valor_proyectado_5_anos_mxn" numeric(15,2),
  "apreciacion_anual_porcentaje" numeric(5,2),
  "tipo_rendimiento" text,
  "plataformas_renta" text[],
  "fotos_unidad" text[],
  "foto_portada_unidad" text,
  "video_recorrido_unidad" text,
  "tour_virtual_unidad" text,
  "plano_unidad" text,
  "renders_3d_unidad" text[],
  "video_drone_unidad" text,
  "galeria_amenidades_unidad" text[],
  "calificacion_unidad" numeric(3,2),
  "numero_resenas_unidad" integer DEFAULT 0,
  "calificacion_ubicacion" numeric(3,2),
  "calificacion_construccion" numeric(3,2),
  "ext_calificacion_valor" numeric(3,2),
  "ext_calificacion_amenidades" numeric(3,2),
  "ext_calificacion_desarrollador" numeric(3,2),
  "meta_title_unidad" text,
  "meta_description_unidad" text,
  "keywords_unidad" text[],
  "og_image_unidad" text,
  "ext_fuente_campana" text,
  "ext_canal_adquisicion" text,
  "ext_vistas" integer DEFAULT 0,
  "ext_guardados" integer DEFAULT 0,
  "ext_contactos" integer DEFAULT 0,
  "ext_citas" integer DEFAULT 0,
  "escritura_disponible" boolean,
  "licencia_construccion" boolean,
  "regimen_propiedad" text,
  "fideicomiso_requerido" boolean,
  "ext_predial_vigente" boolean,
  "ext_cert_libertad_gravamen" boolean,
  "ext_url_doc_uso_suelo" text,
  "ext_docs_legales" text[],
  "lead_nombre" text,
  "lead_email" text,
  "lead_telefono" text,
  "lead_mensaje" text,
  "lead_fecha" timestamp with time zone,
  "lead_medio" text,
  "lead_estatus" text,
  "ext_reserved_by_contact_id" uuid,
  "ext_reserved_at" timestamp with time zone,
  "ext_sold_at" timestamp with time zone,
  "id_desarrollo" uuid,
  "id_desarrollador" uuid,
  "id_agente" uuid,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  "deleted_at" timestamp with time zone,
  "zoho_record_id" text,
  "zoho_last_synced_at" timestamp with time zone,
  "zoho_sync_error" text,
  "approved_at" timestamp with time zone,
  "approved_by" text,
  "zoho_pipeline_status" text DEFAULT 'discovery'::text,
  CONSTRAINT "Propyte_unidades_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_unidades_slug_unidad_key" UNIQUE ("slug_unidad"),
  CONSTRAINT "propyte_unidades_legacy_id_key" UNIQUE ("legacy_id")
);

-- === TABLE Propyte_zoho_leads ===
CREATE TABLE real_estate_hub."Propyte_zoho_leads" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "zoho_record_id" text NOT NULL,
  "first_name" text,
  "last_name" text,
  "email" text,
  "phone" text,
  "mobile" text,
  "company" text,
  "lead_source" text,
  "lead_status" text,
  "owner_name" text,
  "owner_id" text,
  "nombre_campana" text,
  "nombre_anuncio" text,
  "plataforma_llegada" text,
  "nombre_formulario" text,
  "proyecto_interes_ids" text[],
  "interes" text,
  "mensaje" text,
  "idioma" text,
  "broker" boolean DEFAULT false,
  "candidato" boolean DEFAULT false,
  "duplicado" boolean DEFAULT false,
  "etapa_interna" text[],
  "llamada_1" boolean DEFAULT false,
  "llamada_2" boolean DEFAULT false,
  "llamada_3" boolean DEFAULT false,
  "llamada_4" boolean DEFAULT false,
  "llamada_5" boolean DEFAULT false,
  "llamada_6" boolean DEFAULT false,
  "llamada_7" boolean DEFAULT false,
  "llamada_8" boolean DEFAULT false,
  "whatsapp_1" boolean DEFAULT false,
  "whatsapp_2" boolean DEFAULT false,
  "whatsapp_3" boolean DEFAULT false,
  "correo_1" boolean DEFAULT false,
  "correo_2" boolean DEFAULT false,
  "correo_3" boolean DEFAULT false,
  "correo_4" boolean DEFAULT false,
  "city" text,
  "state" text,
  "country" text,
  "gclid" text,
  "ad_campaign_name" text,
  "adgroup_name" text,
  "extra_fields" jsonb DEFAULT '{}'::jsonb,
  "zoho_created_time" timestamp with time zone,
  "zoho_modified_time" timestamp with time zone,
  "synced_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_zoho_leads_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_zoho_leads_zoho_record_id_key" UNIQUE ("zoho_record_id")
);

-- === TABLE Propyte_zoho_accounts ===
CREATE TABLE real_estate_hub."Propyte_zoho_accounts" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "zoho_record_id" text NOT NULL,
  "account_name" text,
  "phone" text,
  "website" text,
  "industry" text,
  "billing_city" text,
  "billing_state" text,
  "billing_country" text,
  "owner_name" text,
  "owner_id" text,
  "extra_fields" jsonb DEFAULT '{}'::jsonb,
  "zoho_created_time" timestamp with time zone,
  "zoho_modified_time" timestamp with time zone,
  "synced_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_zoho_accounts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_zoho_accounts_zoho_record_id_key" UNIQUE ("zoho_record_id")
);

-- === TABLE Propyte_zoho_contacts ===
CREATE TABLE real_estate_hub."Propyte_zoho_contacts" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "zoho_record_id" text NOT NULL,
  "first_name" text,
  "last_name" text,
  "email" text,
  "phone" text,
  "mobile" text,
  "account_name" text,
  "account_zoho_id" text,
  "owner_name" text,
  "owner_id" text,
  "mailing_city" text,
  "mailing_state" text,
  "mailing_country" text,
  "extra_fields" jsonb DEFAULT '{}'::jsonb,
  "zoho_created_time" timestamp with time zone,
  "zoho_modified_time" timestamp with time zone,
  "synced_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_zoho_contacts_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_zoho_contacts_zoho_record_id_key" UNIQUE ("zoho_record_id")
);

-- === TABLE Propyte_zoho_deals ===
CREATE TABLE real_estate_hub."Propyte_zoho_deals" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "zoho_record_id" text NOT NULL,
  "deal_name" text,
  "stage" text,
  "amount" numeric(14,2),
  "closing_date" date,
  "lead_source" text,
  "monto_apartado" numeric(14,2),
  "monto_enganche" numeric(14,2),
  "precio_lista" numeric(14,2),
  "precio_final" numeric(14,2),
  "saldo_contraentrega" numeric(14,2),
  "mensualidades" integer,
  "descuento_autorizado" numeric(14,2),
  "metodo_pago" text,
  "fecha_apartado" date,
  "fecha_procesamiento" date,
  "estatus_contrato" text,
  "carta_oferta_aceptada" text,
  "cotizacion_enviada" boolean DEFAULT false,
  "url_contrato_enviado" text,
  "url_contrato_firmado" text,
  "url_comprobante_domicilio" text,
  "formato_kyc" text,
  "comprobante_enganche" text,
  "recibo_enganche" text,
  "mobiliario" text,
  "contact_zoho_id" text,
  "account_zoho_id" text,
  "proyecto_inmobiliario_zoho_id" text,
  "broker_asociado_zoho_id" text,
  "owner_name" text,
  "owner_id" text,
  "razon_descarte" text,
  "razon_perdida" text,
  "promocion" text,
  "extra_fields" jsonb DEFAULT '{}'::jsonb,
  "zoho_created_time" timestamp with time zone,
  "zoho_modified_time" timestamp with time zone,
  "synced_at" timestamp with time zone DEFAULT now(),
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_zoho_deals_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_zoho_deals_zoho_record_id_key" UNIQUE ("zoho_record_id")
);

-- === TABLE Propyte_zoho_id_map ===
CREATE TABLE real_estate_hub."Propyte_zoho_id_map" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "entity_type" text NOT NULL,
  "supabase_id" text NOT NULL,
  "zoho_module" text NOT NULL,
  "zoho_record_id" text NOT NULL,
  "last_synced_at" timestamp with time zone DEFAULT now(),
  "last_sync_status" text DEFAULT 'success'::text,
  "supabase_updated_at" timestamp with time zone,
  "zoho_modified_time" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_zoho_id_map_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Propyte_zoho_id_map_entity_type_supabase_id_key" UNIQUE ("entity_type", "supabase_id"),
  CONSTRAINT "Propyte_zoho_id_map_zoho_module_zoho_record_id_key" UNIQUE ("zoho_module", "zoho_record_id")
);

-- === TABLE Propyte_historial_precios ===
CREATE TABLE real_estate_hub."Propyte_historial_precios" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "id_unidad" uuid,
  "fecha" date NOT NULL,
  "precio_mxn" numeric(15,2),
  "tipo_movimiento" text,
  "cambio_porcentaje" numeric(5,2),
  "razon" text,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_historial_precios_pkey" PRIMARY KEY ("id")
);

-- === TABLE Propyte_resenas ===
CREATE TABLE real_estate_hub."Propyte_resenas" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "id_unidad" uuid,
  "nombre_usuario" text,
  "fecha" date,
  "comentario" text,
  "calificacion" numeric(3,2),
  "verificada" boolean DEFAULT false,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "Propyte_resenas_pkey" PRIMARY KEY ("id")
);

-- === VIEW v_developers ===
CREATE OR REPLACE VIEW real_estate_hub."v_developers" AS
 SELECT id,
    legacy_id,
    nombre_desarrollador AS name,
    ext_slug_desarrollador AS slug,
    logo AS logo_url,
    sitio_web AS website,
    telefono AS phone,
    email,
    descripcion AS description_es,
    ext_descripcion_en AS description_en,
    ext_ciudad AS city,
    ext_estado AS state,
    es_verificado AS verified,
    nombre_contacto AS contact_name,
    puesto_contacto AS contact_title,
    redes_sociales AS social_media,
    calificacion AS rating,
    proyectos_activos AS active_projects,
    unidades_entregadas AS delivered_units,
    anos_experiencia AS years_experience,
    proyectos_entregados AS delivered_projects,
    created_at,
    updated_at,
    deleted_at,
    approved_at,
    approved_by,
    zoho_pipeline_status
   FROM real_estate_hub."Propyte_desarrolladores";

-- === VIEW v_developments ===
CREATE OR REPLACE VIEW real_estate_hub."v_developments" AS
 SELECT d.id,
    d.legacy_id,
    d.ext_slug_desarrollo AS slug,
    d.nombre_desarrollo AS name,
    d.id_desarrollador AS developer_id,
    d.tipo_desarrollo AS development_type,
    d.etapa_construccion AS stage,
    d.avance_obra_porcentaje AS construction_progress,
    d.fecha_entrega AS estimated_delivery,
    d.ext_fecha_entrega_texto AS delivery_text,
    d.unidades_totales AS total_units,
    d.unidades_disponibles AS available_units,
    d.ext_reserved_units AS reserved_units,
    d.ext_sold_units AS sold_units,
    d.fotos_desarrollo AS images,
    d.url_drive_general AS drive_url,
    d.lista_precios AS price_list_url,
    d.brochure_pdf AS brochure_url,
    d.tour_virtual_desarrollo AS virtual_tour_url,
    d.masterplan,
    d.video_desarrollo AS video_url,
    d.ext_precio_min_mxn AS price_min_mxn,
    d.ext_precio_max_mxn AS price_max_mxn,
    d.ext_moneda AS currency,
    d.ext_roi_proyectado AS roi_projected,
    d.ext_roi_renta_mensual AS roi_rental_monthly,
    d.ext_roi_apreciacion AS roi_appreciation,
    d.ext_enganche_porcentaje AS financing_down_payment,
    d.ext_meses_financiamiento AS financing_months,
    d.ext_tasa_interes AS financing_interest,
    d.ext_descripcion_es AS description_es,
    d.ext_descripcion_en AS description_en,
    d.ext_descripcion_corta_es AS description_short_es,
    d.ext_descripcion_corta_en AS description_short_en,
    d.ext_meta_title_desarrollo AS meta_title,
    d.ext_meta_description_desarrollo AS meta_description,
    d.ext_keywords AS keywords,
    d.ext_destacado AS featured,
    d.ext_publicado AS published,
    d.pais AS country,
    d.estado AS state,
    d.municipio AS municipality,
    d.ciudad AS city,
    d.colonia AS neighborhood,
    d.calle AS address,
    d.codigo_postal AS zip_code,
    d.latitud AS lat,
    d.longitud AS lng,
    d.zona AS zone,
    d.link_maps AS maps_url,
    d.playa_distancia AS beach_distance,
    d.aeropuerto_nombre AS airport_name,
    d.aeropuerto_distancia AS airport_distance,
    d.puntos_interes AS points_of_interest,
    d.ext_crm_relationship AS crm_relationship,
    d.ext_commission_rate AS commission_rate,
    d.ext_property_types AS property_types,
    d.ext_usage AS usage,
    d.ext_badge AS badge,
    d.ext_plaza AS plaza,
    d.ext_contacto_nombre AS contact_name,
    d.ext_contacto_telefono AS contact_phone,
    d.ext_detection_source AS detection_source,
    d.ext_source_url AS source_url,
    d.ext_detected_at AS detected_at,
    d.created_at,
    d.updated_at,
    d.deleted_at,
    dev.nombre_desarrollador AS developer_name,
    dev.ext_slug_desarrollador AS developer_slug,
    d.approved_at,
    d.approved_by,
    d.zoho_pipeline_status
   FROM real_estate_hub."Propyte_desarrollos" d
     LEFT JOIN real_estate_hub."Propyte_desarrolladores" dev ON d.id_desarrollador = dev.id;

-- === VIEW v_units ===
CREATE OR REPLACE VIEW real_estate_hub."v_units" AS
 SELECT u.id,
    u.legacy_id,
    u.slug_unidad AS slug,
    u.titulo_unidad AS title,
    u.subtitulo_unidad AS subtitle,
    u.descripcion_corta_unidad AS description_short,
    u.descripcion_larga_unidad AS description_es,
    u.ext_descripcion_en AS description_en,
    u.id_desarrollo AS development_id,
    u.id_desarrollador AS developer_id,
    u.id_agente AS agent_id,
    u.ext_numero_unidad AS unit_number,
    u.tipo_unidad AS unit_type,
    u.subtipo_unidad AS unit_subtype,
    u.ext_tipologia AS typology,
    u.estado_unidad AS status,
    u.es_nueva_unidad AS is_new,
    u.es_destacada_unidad AS featured,
    u.es_preventa AS is_presale,
    u.ext_publicado AS published,
    u.recamaras AS bedrooms,
    u.banos_completos AS bathrooms,
    u.medios_banos AS half_baths,
    u.superficie_total_m2 AS area_m2,
    u.superficie_construida_m2 AS built_area_m2,
    u.superficie_terreno_m2 AS lot_area_m2,
    u.niveles_unidad AS floors,
    u.piso_numero AS floor,
    u.estacionamientos AS parking_spots,
    u.orientacion AS orientation,
    u.vista_unidad AS view,
    u.amueblado AS furnished,
    u.equipado AS equipped,
    u.mascotas_permitidas AS pets_allowed,
    u.ext_tiene_alberca AS has_pool,
    u.precio_mxn AS price_mxn,
    u.precio_usd AS price_usd,
    u.precio_m2_mxn AS price_per_m2_mxn,
    u.precio_m2_usd AS price_per_m2_usd,
    u.moneda_principal AS currency,
    u.precio_desde AS price_from,
    u.enganche_porcentaje AS down_payment_pct,
    u.ext_enganche_mxn AS down_payment_mxn,
    u.ext_mensualidad_mxn AS monthly_payment_mxn,
    u.ext_precio_venta AS sale_price,
    u.roi_anual_porcentaje AS roi_annual,
    u.renta_mensual_estimada_mxn AS estimated_monthly_rent_mxn,
    u.apreciacion_anual_porcentaje AS annual_appreciation,
    u.plataformas_renta AS rental_platforms,
    u.fotos_unidad AS images,
    u.foto_portada_unidad AS cover_image,
    u.video_recorrido_unidad AS video_url,
    u.tour_virtual_unidad AS virtual_tour_url,
    u.plano_unidad AS floor_plan_url,
    u.calificacion_unidad AS rating,
    u.numero_resenas_unidad AS review_count,
    u.meta_title_unidad AS meta_title,
    u.meta_description_unidad AS meta_description,
    u.keywords_unidad AS keywords,
    u.ext_reserved_by_contact_id AS reserved_by_contact_id,
    u.ext_reserved_at AS reserved_at,
    u.ext_sold_at AS sold_at,
    u.created_at,
    u.updated_at,
    u.deleted_at,
    d.nombre_desarrollo AS development_name,
    d.ext_slug_desarrollo AS development_slug,
    d.ciudad AS city,
    d.estado AS state,
    d.zona AS zone,
    dev.nombre_desarrollador AS developer_name,
    u.approved_at,
    u.approved_by,
    u.zoho_pipeline_status
   FROM real_estate_hub."Propyte_unidades" u
     LEFT JOIN real_estate_hub."Propyte_desarrollos" d ON u.id_desarrollo = d.id
     LEFT JOIN real_estate_hub."Propyte_desarrolladores" dev ON u.id_desarrollador = dev.id;
